#pragma once

#define TEST_WINDOW 0
#define TEST_WINDOW_INPUT 0
#define TEST_ALPHA_BLENDING 0
#define TEST_STRING 0
#define TEST_FILEIO 0
#define TEST_BITMAP 0
#define TEST_COMPONENT 0
#define TEST_COMPONENT_TREE 1